### ISSUE TITLE
axios-cache-hooks peer depencies cannot be satisfied since there is no "axios": ">=0.28" as of now.

### ISSUE THREAD

**Issue by midnights-straychild** [arthurfiorette/tinylibs#153]
Currently latest version of axios is 0.27.2 which is also stated in the devDependencies as well.

Is that a mistake?

**Comment by arthurfiorette** [comment]
Hey, actually no. The axios-cache-hooks is a very effective project, but currently does not work with any axios version because of axios/axios#4922, axios/axios#4659 and axios/axios#4711. These PRs were opened before axios started moving to a 1.X stable version, and they're probably still stale because of it.

Can you ping jasonsaayman at axios/axios#4922?
